"""User and MentorProfile tables.

Revision ID: 0002
Revises: 0001
Create Date: 2025-05-05

Creates the core user tables:
- user: Authenticated users with soft-delete support
- mentor_profile: Optional mentor extension for users

Key constraints:
- user.cognito_sub is globally unique
- user.email is unique ONLY among active users (partial index)
- mentor_profile.user_id is unique (one-to-one with user)
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # === USER TABLE ===
    op.create_table(
        "user",
        # Primary key - UUID generated by PostgreSQL
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        # Cognito subject ID - links to AWS Cognito identity
        sa.Column("cognito_sub", sa.String(255), nullable=False),
        # Email - uniqueness enforced by partial index below
        sa.Column("email", sa.String(255), nullable=False),
        # Display name - optional, shown in UI
        sa.Column("display_name", sa.String(100), nullable=True),
        # Avatar URL - optional profile picture
        sa.Column("avatar_url", sa.String(500), nullable=True),
        # Timestamps (from TimestampMixin)
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Soft-delete timestamp (from SoftDeleteMixin)
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Index on cognito_sub for fast JWT lookups
    op.create_index("ix_user_cognito_sub", "user", ["cognito_sub"], unique=True)

    # Index on deleted_at for soft-delete filtering
    op.create_index("ix_user_deleted_at", "user", ["deleted_at"])

    # PARTIAL UNIQUE INDEX: email must be unique, but only for active users
    # This allows reusing an email after the original user is soft-deleted
    op.execute(
        """
        CREATE UNIQUE INDEX ix_user_email_active
        ON "user" (email)
        WHERE deleted_at IS NULL
        """
    )

    # Trigger to auto-update updated_at on row changes
    op.execute(
        """
        CREATE TRIGGER update_user_updated_at
        BEFORE UPDATE ON "user"
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at()
        """
    )

    # === MENTOR_PROFILE TABLE ===
    op.create_table(
        "mentor_profile",
        # Primary key
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        # Foreign key to user - UNIQUE enforces one-to-one
        sa.Column(
            "user_id",
            sa.UUID(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        # Bio - longer text description
        sa.Column("bio", sa.Text(), nullable=True),
        # Headline - short tagline
        sa.Column("headline", sa.String(200), nullable=True),
        # Is mentor enabled? (admin can disable)
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default="true"),
        # Rating aggregates (computed by trigger in Step 3.4)
        sa.Column("rating_avg", sa.Numeric(3, 2), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False, server_default="0"),
        # Last activity timestamp
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        # Timestamps
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # Index on user_id for fast lookups (also enforces uniqueness)
    op.create_index("ix_mentor_profile_user_id", "mentor_profile", ["user_id"])

    # Trigger to auto-update updated_at
    op.execute(
        """
        CREATE TRIGGER update_mentor_profile_updated_at
        BEFORE UPDATE ON mentor_profile
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at()
        """
    )


def downgrade() -> None:
    # Drop triggers first (they depend on tables)
    op.execute(
        "DROP TRIGGER IF EXISTS update_mentor_profile_updated_at ON mentor_profile"
    )
    op.execute('DROP TRIGGER IF EXISTS update_user_updated_at ON "user"')

    # Drop tables (indexes are dropped automatically)
    op.drop_table("mentor_profile")
    op.drop_table("user")
